### ISSUE TITLE
界面定制怎么操作的

### ISSUE THREAD

**Issue by wanghaisheng** [amisadmin/fastapi_amis_admin_demo#3]
能直接更新从editor编辑得到的json吗

**Comment by amisadmin** [comment]
通过继承`PageAdmin`可以自己配置amis页面json, 后台动态添加json的功能,后期有时间了会拓展

**Comment by wanghaisheng** [comment]
现在呢  怎么操作

**Comment by amisadmin** [comment]
> 

通过继承PageAdmin可以自己配置amis页面json

**Comment by wanghaisheng** [comment]
比如userauthdemo的login页面 我只看到了pageschema
你意思是
我抄一个这个 准备一个塞好了json的html？
@site.register_admin
class ElementTemplateAdmin(DemoJinja2Admin):
    page_schema = PageSchema(label='ElementUI', icon='fa fa-link')
    template_name = 'element.html'

**Comment by amisadmin** [comment]
> 比如userauthdemo的login页面 我只看到了pageschema 你意思是 我抄一个这个 准备一个塞好了json的html？ @site.register_admin class ElementTemplateAdmin(DemoJinja2Admin): page_schema = PageSchema(label='ElementUI', icon='fa fa-link') template_name = 'element.html'

```python
@site.register_admin
class HelloWorldPageAdmin(admin.PageAdmin):
    group_schema = 'Page'
    page_schema = PageSchema(label='HelloWorld', icon='fa fa-link')
    # 通过page类属性直接配置页面信息;
    # Page组件支持属性参考: https://baidu.gitee.io/amis/zh-CN/components/page
    page = Page(title='标题', body='Hello World!')
```
这里的page你可以任意修改, 
Page.parse_obj({
    这里可以写任何amis能够识别的json
})

**Comment by wanghaisheng** [comment]
fastapi_user_auth_demo里
没找到类似HelloWorldPageAdmin 和admin.PageAdmin
fastapi_amis_admin_demo里倒是有
